//
//  ClipboardHistoryStore.swift
//  TeleDeckMac
//
//  Macのクリップボード変化を監視し、コピー履歴を保持する。NSPasteboardには変化通知の
//  API が無いため、changeCountを一定間隔でポーリングする方式を取る（クリップボード管理系
//  アプリ全般が採用している標準的な手法）。
//
//  履歴はディスクへ永続化せず、アプリのメモリ上にのみ保持する（プロファイル設定とは異なり、
//  機微な文字列が残り続けるリスクを避けるため、アプリ再起動でクリアされる仕様とする）。
//

import AppKit
import Foundation

final class ClipboardHistoryStore {
  private struct Item {
    let id = UUID()
    let kind: ClipboardItemKind
    let textValue: String?
    /// 貼り付け時に使う原本データ（ネットワークには載せない）
    let imageData: Data?
    let imageThumbnailBase64: String?
    let timestamp: Date
  }

  enum PasteError: LocalizedError {
    case itemNotFound

    var errorDescription: String? {
      switch self {
      case .itemNotFound:
        return "履歴アイテムが見つかりません"
      }
    }
  }

  /// 履歴一覧が変化するたびに、ネットワーク送信用の形へ変換済みの一覧を渡して呼ばれる
  var onChange: (([ClipboardHistoryEntry]) -> Void)?

  private var items: [Item] = []
  private var lastChangeCount: Int
  private var timer: Timer?

  private static let maxItems = 30
  private static let maxTextPreviewLength = 2000
  private static let maxImageDataSize = 15_000_000
  private static let thumbnailMaxDimension: CGFloat = 240
  private static let pollInterval: TimeInterval = 0.5

  /// パスワードマネージャー等が「クリップボード履歴に残さないでほしい」という意図で付与する、
  /// 非公式だが広く尊重されている型。付与されている場合は履歴に記録しない
  private static let sensitivePasteboardTypes: Set<NSPasteboard.PasteboardType> = [
    NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
  ]

  init() {
    lastChangeCount = NSPasteboard.general.changeCount
  }

  /// ポーリングを開始する。メニューのトラッキング中などでも止まらないよう`.common`モードで登録する
  func start() {
    let newTimer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
      self?.pollPasteboard()
    }
    RunLoop.main.add(newTimer, forMode: .common)
    timer = newTimer
  }

  func stop() {
    timer?.invalidate()
    timer = nil
  }

  var networkEntries: [ClipboardHistoryEntry] {
    items.map(Self.makeEntry)
  }

  /// 指定した履歴アイテムをMacのクリップボードにセットする（実際のCmd+V送信は呼び出し側に委ねる）
  func pasteItem(id: UUID, completion: @escaping (Result<Void, Error>) -> Void) {
    guard let item = items.first(where: { $0.id == id }) else {
      completion(.failure(PasteError.itemNotFound))
      return
    }

    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    switch item.kind {
    case .text:
      pasteboard.setString(item.textValue ?? "", forType: .string)
    case .image:
      if let imageData = item.imageData {
        pasteboard.setData(imageData, forType: .tiff)
      }
    }
    // ここで発生するchangeCountの変化を、次のポーリングが「新規コピー」として
    // 誤って履歴に取り込まないよう、先に同期しておく
    lastChangeCount = pasteboard.changeCount

    completion(.success(()))
  }

  // MARK: - ポーリング

  private func pollPasteboard() {
    let pasteboard = NSPasteboard.general
    guard pasteboard.changeCount != lastChangeCount else { return }
    lastChangeCount = pasteboard.changeCount

    let types = pasteboard.types ?? []
    guard !types.contains(where: Self.sensitivePasteboardTypes.contains) else { return }

    if let imageData = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png),
       imageData.count <= Self.maxImageDataSize,
       let image = NSImage(data: imageData) {
      guard items.first?.imageData != imageData else { return }
      let thumbnail = Self.makeThumbnailBase64(from: image)
      insert(Item(kind: .image, textValue: nil, imageData: imageData, imageThumbnailBase64: thumbnail, timestamp: Date()))
    } else if let text = pasteboard.string(forType: .string), !text.isEmpty {
      guard items.first?.textValue != text else { return }
      insert(Item(kind: .text, textValue: text, imageData: nil, imageThumbnailBase64: nil, timestamp: Date()))
    }
  }

  private func insert(_ item: Item) {
    items.insert(item, at: 0)
    if items.count > Self.maxItems {
      items.removeLast(items.count - Self.maxItems)
    }
    onChange?(networkEntries)
  }

  // MARK: - 変換・サムネイル生成

  private static func makeEntry(from item: Item) -> ClipboardHistoryEntry {
    ClipboardHistoryEntry(
      id: item.id,
      kind: item.kind,
      textPreview: item.textValue.map { String($0.prefix(Self.maxTextPreviewLength)) },
      imageThumbnailBase64: item.imageThumbnailBase64,
      timestamp: item.timestamp
    )
  }

  private static func makeThumbnailBase64(from image: NSImage) -> String? {
    let size = image.size
    guard size.width > 0, size.height > 0 else { return nil }

    let scale = min(1, thumbnailMaxDimension / max(size.width, size.height))
    let targetSize = NSSize(width: size.width * scale, height: size.height * scale)

    let thumbnail = NSImage(size: targetSize)
    thumbnail.lockFocus()
    image.draw(in: NSRect(origin: .zero, size: targetSize))
    thumbnail.unlockFocus()

    guard let tiffData = thumbnail.tiffRepresentation,
          let bitmap = NSBitmapImageRep(data: tiffData),
          let jpegData = bitmap.representation(using: .jpeg, properties: [.compressionFactor: 0.6]) else {
      return nil
    }
    return jpegData.base64EncodedString()
  }
}
